eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
server:
  port: 8080
spring:
  application:
    name: itsgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders:
              - "Authorization"
              - "X-Forwarded-For"
              - "X-its-alert"
              - "X-its-alertParam"
              - "X-its-rptFile"
              - "X-its-errorCode"
              - "X-its-errorParam"          
      routes:
      - id: itsaccount
        uri: lb://itsaccount
        predicates:
        - Path=/account/**
      - id: itsauthen
        uri: lb://itsauthen
        predicates:
        - Path=/authentication/**
      - id: itsmarketdata
        uri: lb://itsmarketdata
        predicates:
        - Path=/marketdata/**
      - id: itsorder
        uri: lb://itsorder
        predicates:
        - Path=/order/**
      - id: itsstaticdata
        uri: lb://itsstaticdata
        predicates:
        - Path=/staticdata/**