eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
server:
  port: 8080
spring:
  application:
    name: itsgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true      
      routes:
      - id: itsaccount
        uri: lb://itsaccount
        predicates:
        - Path=/account-serv/**
      - id: itsauthen
        uri: lb://itsauthen
        predicates:
        - Path=/authen-serv/**
      - id: itsmarketdata
        uri: lb://itsmarketdata
        predicates:
        - Path=/market-data/**
      - id: itsorder
        uri: lb://itsorder
        predicates:
        - Path=/order-serv/**
      - id: itsstaticdata
        uri: lb://itsstaticdata
        predicates:
        - Path=/static-data/**